apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-js-app
  labels:
    app: node-js-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-js-app
  template:
    metadata:
      labels:
        app: node-js-app
    spec:
      containers:
      - name: node-js-app
        image: gshrey2002/nodecicd:replaceImageTag
        ports:
        - containerPort: 8080
